### ISSUE TITLE
Bootloop on 15.0410.1801.40

### ISSUE THREAD

**Issue by lukaspieper** [Planet-X/android_device_asus_zenfone3#1]
Hi,

I just unlocked my bootloader unoffically and update to 15.0410.1801.40 (Oreo from Feb 12). 
On XDA two users reportet bootloop with your latest TWRP:

1. https://forum.xda-developers.com/zenfone-3/how-to/guide-how-to-root-zenfone-3-official-t3745650/page2 (post from siberflyers)

2. https://forum.xda-developers.com/zenfone-3/development/recovery-twrp-3-2-1-ze520kl-ze552kl-t3742765/page6 (post from jackychu89)

Do you have any News on this?

Thanks!

**Comment by Planet-X** [comment]
I'm not exactly a stock rom expert but simply installing twrp should never cause a bootloop as it is on a different partition than stock rom. Its always what you do in twrp that may cause bootloops.
It seems to work for almost all users, even with stock rom 15.0410.1801.40.
Additionally OP from [here](https://forum.xda-developers.com/zenfone-3/how-to/guide-how-to-root-zenfone-3-official-t3745650) added an update and rooting guide for 15.0410.1801.40 to the first post so it really seems to work.

**Comment by lukaspieper** [comment]
Ok, thanks. I'm just being cautious because I've never rooted stock android before. But I'll try, thanks.

**Comment by Planet-X** [comment]
No problem! Better save than sorry!

**Comment by lukaspieper** [comment]
Your TWRP works fine, no bootloop. I also installed Magisk 16 successfully. Thanks again. You can close this "issue" ;-)

**Comment by Planet-X** [comment]
Thanks for reporting back! Issue closed.
