### ISSUE TITLE
Settings hang on Connected devices

### ISSUE THREAD

**Issue by LightWayUp** [Planet-X/android_device_asus_zenfone3#3]
Settings hang upon entering Connected devices. Phone sometimes needs a reboot to recover from the hang, while other times it recovers after approximately 15~30 seconds.
All of the categories seems to work fine without any crash, hang or freeze ( Bluetooth, Printing, Cast ). However, upon exiting those pages and back to Connected devices, Settings still freezes for a few seconds.

This happened to me on all builds of LineageOS 14.1 and 15.1 for ZE520KL, but official ASUS firmware works fine ( I flashed Oreo raw firmware to confirm ).

This happens both with and without Advanced Kernel ( to at least v0.2 ).

**Comment by Planet-X** [comment]
Thanks for your detailed report!
This problem has already been brought up by some other users but I was never able to reproduce it on my phone. Would you mind collecting some logs (dmesg and logcat)?
Maybe they can point to the right direction.

**Comment by LightWayUp** [comment]
Sure :). But I'm not quite familiar to these... When should I run the commands to take logcat and dmesg?

**Comment by Planet-X** [comment]
Great, could be really helpful!
First, right before entering the "Connected devices" page, you should clear the logs via `adb logcat -c` and `adb shell dmesg -c` so that only relevant entries are included. Next enter the page so that the issue occurs. Shortly afterwards, while the phone's still stuck, you can collect the dmesg and logcat logs over the hopefully still working adb connection.

**Comment by LightWayUp** [comment]
Actually I'm not so sure that the culprit is Bluetooth anymore... I originally thought so because upon entering the page it hangs and crashes, but now I realize it happens to "Cast" and "Printing" as well, all of them are in "Connect devices" 😅 . I'm sure, however, that Bluetooth page did exhibit such behavior on LineageOS 14.1 as well.

I'm not sure if the logs contain what you'll need, but I saved all of the ones I managed to capture. Here's the link to the files ( in my Google Drive folders ): https://drive.google.com/drive/folders/1yFRnQuhDaXAfa7AD7MjwFJHGefRFWNH5?usp=sharing

**Comment by Planet-X** [comment]
Thanks for collecting them!
I'll take a look and let you know if I found something.

**Comment by LightWayUp** [comment]
Ok, thanks!

**Comment by LightWayUp** [comment]
Has anything been found?

**Comment by Planet-X** [comment]
Sadly no...
I couldn't find anything special in the logs or reproduce this behavior on my phone.

**Comment by LightWayUp** [comment]
I think I've put the focus on the wrong place... After doing some more testing, I found that all of the categories works fine without any crash, hang or freeze ( Bluetooth, Printing, Cast ). However, upon *exiting* those pages Settings still freezes for a few seconds. I think the freeze that happens when accessing Bluetooth after first boot was because Android was also trying to load Connected devices page. Afterwards, as long as the page wasn't entered directly ( for example, long press the Bluetooth tile from Quick Settings instead ), no freezing occurs.
I have no idea why or what is causing this either, and searching online yields no relevant results about this bizarre behavior. Do you think I should close this issue?
On a side note, I installed Lineage OS 14.1 while being on official Marshmallow firmware. When 15.1 came out, I flashed the raw image for Oreo firmware to update other partitions, and then installed Lineage OS 15.1 ( which means I've never updated to official Nougat firmware ). Could specific partitions be updated with Nougat firmware update, but not with Oreo's? I'm not sure if that's even possible, but if it is the case, could I still have partitions using Marshmallow's stuff, causing weird behavior?

**Comment by LightWayUp** [comment]
I know this issue has been closed for a while, but I'm reporting back that after flashing the latest Oreo raw firmware, the issue seems to have been resolved. Still thanks for looking into the issue!

For everyone having the issue, try flashing latest Oreo raw firmware, then completely wiping and formatting to clean install Lineage OS again. This *might* solve the issue.
